Fix test that depend on the local timezone (#197)
Running the test with a specific local timezone could make the test
fail, for example:

    TZ=Etc/GMT+12 go test ./torrent/

...resulted in the following failure:

  --- FAIL: TestShowTorrentInfo_Complete (0.00s)
      --- FAIL: TestShowTorrentInfo_Complete/Complete_torrent_with_all_fields (0.00s)
          display_test.go:282:
              	Error Trace:	/home/nicolas/debian/mkbrr/torrent/display_test.go:282
              	Error:      	"[truncated]\n  Created on:   2021-12-31 12:00:00 -12\n  Files:        2\n\n" does not contain "Created on:   2022-01-01"
              	Test:       	TestShowTorrentInfo_Complete/Complete_torrent_with_all_fields
              	Messages:   	Output should contain line: Created on:   2022-01-01

We now output the expected date in the local timezone to match the
actual output.